version: '3.3'
services:
  mongo_db:
    container_name: dockermicroservices_mongo_db
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    container_name: dockermicroservices_ui
    build: ./ui
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
  post:
    container_name: dockermicroservices_post
    build: ./post-py
    image: ${USERNAME}/post:${VERSION}
    networks:
      - front_net
      - back_net
  comment:
    container_name: dockermicroservices_comment
    build: ./comment
    image: ${USERNAME}/comment:${VERSION}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
